#!/bin/bash
./streamer -t ws://localhost:8082/ -r ws://localhost:8083/ -v
#./streamer -t ws://localhost:8082/ -r ws://jsmpeg.practable.io:80/ws/camera/ -v
#./streamer -t ws://localhost:8082/ -r ws://localhost:8011 -v

